apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: food-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cfg-labs/gcp-shared-traffic-demo.git
    targetRevision: HEAD
    path: apps/article-05/cfg-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: cfg-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
